### ISSUE TITLE
Textbox problem in `demo.nim`

### ISSUE THREAD

**Issue by matkuki** [elcritch/fidgetty#19]
When clicking in the textbox of the `demo.nim` example when there is no text yet in the textbox,
the cursor appears at a weird position (highlighted in red):
![image](https://user-images.githubusercontent.com/10289651/194387016-2b514833-1234-45a1-87ad-e83b2ef05288.png)
Shouldn't it be in the center of the textbox, or at least nicely aligned to the left (not in the border)?

**Comment by elcritch** [comment]
Yes... That quirk has been bugging me for a while. Unfortunately the layout of the cursor relies on the `typeography` package that is sorta stale. However, Fidgetty has a patched version of `TextBox` from `typeography` which handles the layout. 

The issue is somewhere around this section of code: https://github.com/elcritch/fidgetty/blob/aec2b9c3922a700ca0238c8f0c114e240975647b/src/fidgetty/fidget_dev/patches/textboxes.nim#L150 

Unfortunately I won't have time to track that guy down for a few weeks.. You could try to take a stab at solving it if you're interested. Really it's just that the TextBox should center the cursor rect when the text alignment is centered even if it's empty. 

>  Shouldn't it be in the center of the textbox, or at least nicely aligned to the left (not in the border)?

Yes I was thinking about borders lately. Borders in Fidget are just stroked lines around the inside of the current node, so the cursor is aligning to the edge of the box properly, but that's not what we really want generally when we think of "border". 

I think it'd be better to have borders go outward or to create a smaller inner rect for the layout. Though it'd change the layout of widgets and things. What are your thoughts on including borders in the layout?

**Comment by matkuki** [comment]
> I think it'd be better to have borders go outward or to create a smaller inner rect for the layout.

I'm quite familiar with `Qt` and that's how they do it: `to create a smaller inner rect for the layout`.

I'll try and take a look at the alignment issue.

**Comment by matkuki** [comment]
Created #21
Please check it, thanks.
